name: blitzwin
description: BlitzWin betting ios app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  intl: ^0.18.1
  http: ^0.13.5
  fluttertoast: ^8.2.4
  crypto: ^3.0.2
  get_ip_address: ^0.0.5
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^1.1.5
  gradient_borders: ^1.0.0
  persistent_bottom_nav_bar: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: lato-bold
      fonts:
        - asset: assets/fonts/lato-bold.ttf
    - family: lato-regular
      fonts:
        - asset: assets/fonts/lato-regular.ttf